### ISSUE TITLE
To get current location

### ISSUE THREAD

**Issue by isabirahmed** [kelsonpw/react-chrome-extension-router#3]
Firstly thank you for creating this package.
I was wondering if there is any way to get the name/path of the current component.
Similar to props.location supported by react-router.
I know we don't have a path component in your library, but was still wondering if there is any other way to achieve this. 
Thanks.

**Comment by kelsonpw** [comment]
Hey @sabirahmed121 thanks for the issue, I am working on a solution for this problem right now, i will let you know when its ready to go.

Thanks so much for using my package!

**Comment by kelsonpw** [comment]
Hey @sabirahmed121, I just published v1.0.2.  This includes a new `getCurrent` function that returns an object: `{component: CurrentComponent, props: CurrentComponentProps}`

**Comment by kelsonpw** [comment]
I also updated the readme to show how to use this.  Let me know if this doesnt solve your use case

**Comment by sabirahmed121** [comment]
Thanks for the feature!
Will check it out!
